CC=gcc
COMPILE.c=$(CC) $(CFLAGS) $(CPPFLAGS) -c
LINK.c=$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
CFLAGS= -Wall

PROGS =	byteio cmd_action containerof cpmem daemon envi \
	findnumber findsubstr cpuspd getpwd initdarr \
	inotify inotifyep jmp localva strdup parr pbrb \
	recd recdr recdw recu reverstr revert180 scan_cal \
	bigend socketp stack stdouterr structnop swapno \
	threadsync ttyname tdas idx2str pc spa epl inotify_example \
	dnotify_test percent_star_d toggle_value mmap_test1 mmap_test2 \
	mmap_test3w mmap_test3r fsk_demo incomptest selfident \
	prot_fun glob_example print_color

all:	$(PROGS)

print_color : ansi_color.o
		$(CC) $(CFLAGS) -o $@ $^

glob_example : glob_example.o
		$(CC) $(CFLAGS) -o $@ $^

prot_fun : protect_function.o
		$(CC) $(CFLAGS) -o $@ $^

selfident: selfident.o
		$(CC) $(CFLAGS) -o $@ $^

fsk_demo: fseek_example.o
		$(CC) $(CFLAGS) -o $@ $^

mmap_test3w: mmap3_w.o
		$(CC) $(CFLAGS) -o $@ $^

mmap_test3r: mmap3_r.o
		$(CC) $(CFLAGS) -o $@ $^

mmap_test2: mmap2.o
		$(CC) $(CFLAGS) -o $@ $^

mmap_test1: mmap1.o
		$(CC) $(CFLAGS) -o $@ $^

toggle_value: toggle.o
		$(CC) $(CFLAGS) -o $@ $^

percent_star_d: percent_star_d.o
		$(CC) $(CFLAGS) -o $@ $^

dnotify_test: dnotify_test.o
		$(CC) $(CFLAGS) -o $@ $^

spa: struct_point_array.o
		$(CC) $(CFLAGS) -o $@ $^

pc:	pc.o
		$(CC) $(CFLAGS) -o $@ $^ -lpthread

idx2str:	use_index_find_string.o
		$(CC) $(CFLAGS) -o $@ $^

tdas:	two_dimension_array.o
		$(CC) $(CFLAGS) -o $@ $^

ttyname:	ttyname.o
		$(CC) $(CFLAGS) -o $@ $^

threadsync:	thread_sync.o
		$(CC) $(CFLAGS) -o $@ $^ -lpthread

swapno:	swap_numbers.o
		$(CC) $(CFLAGS) -o $@ $^

structnop:	struct_without_pack.o
		$(CC) $(CFLAGS) -o $@ $^

stdouterr:	stdout_stderr.o
		$(CC) $(CFLAGS) -o $@ $^

stack:	stack.o
		$(CC) $(CFLAGS) -o $@ $^

socketp:	socketpair.o
		$(CC) $(CFLAGS) -o $@ $^ -lpthread

bigend:	set_big_endless.o
		$(CC) $(CFLAGS) -o $@ $^

scan_cal:	scan_calculator.o
		$(CC) $(CFLAGS) -o $@ $^

revert180:	revert180.o
		$(CC) $(CFLAGS) -o $@ $^

reverstr:	revers_string.o
		$(CC) $(CFLAGS) -o $@ $^

recu:	recursion.o
		$(CC) $(CFLAGS) -o $@ $^

recdw:	record_write.o
		$(CC) $(CFLAGS) -o $@ $^

recdr:	record_read.o
		$(CC) $(CFLAGS) -o $@ $^

recd:	record.o
		$(CC) $(CFLAGS) -o $@ $^

pbrb:	print_binary_rever_bit.o
		$(CC) $(CFLAGS) -o $@ $^

parr:	point_to_array.o
		$(CC) $(CFLAGS) -o $@ $^

strdup:	mystrdup.o
		$(CC) $(CFLAGS) -o $@ $^

localva:	local_variable.o
		$(CC) $(CFLAGS) -o $@ $^

jmp:	jmp.o
		$(CC) $(CFLAGS) -o $@ $^

epl:	epoll.o
		$(CC) $(CFLAGS) -o $@ $^

inotifyep:	inotify_epoll.o
		$(CC) $(CFLAGS) -o $@ $^

inotify:	inotify.o
		$(CC) $(CFLAGS) -o $@ $^

initdarr:	init_array.o
		$(CC) $(CFLAGS) -o $@ $^

gopt:	getopt.o
		$(CC) $(CFLAGS) -o $@ $^

gopt_long:	getopt_long.o
		$(CC) $(CFLAGS) -o $@ $^

byteio:	byte_io.o
		$(CC) $(CFLAGS) -o $@ $^

cmd_action:	cmd_and_action.o
		$(CC) $(CFLAGS) -o $@ $^

containerof :	container_of.o
		$(CC) $(CFLAGS) -o $@ $^

cpmem :	copy_struct_member.o
		$(CC) $(CFLAGS) -o $@ $^

envi :	environ.o
		$(CC) $(CFLAGS) -o $@ $^

daemon :	daemon.o
		$(CC) $(CFLAGS) -o $@ $^

findnumber :	find_number_in_string.o
		$(CC) $(CFLAGS) -o $@ $^

findsubstr :	find_sub_str.o
		$(CC) $(CFLAGS) -o $@ $^

cpuspd :	get_cpu_speed_from_cpuinfo.o
		$(CC) $(CFLAGS) -o $@ $^

getpwd :	get_exe_path.o
		$(CC) $(CFLAGS) -o $@ $^

inotify_example :	inotify_example.o
		$(CC) $(CFLAGS) -o $@ $^

# gcov test demo
incomptest : incomptest.c
		$(CC) $(CFLAGS) -o $@ $^ -ftest-coverage -fprofile-arcs

clean:
	rm -f $(PROGS) *.o a.out iotestfile log.txt recfile
